const MUNICIPAL_DATA = [
  {
    "id": "111",
    "sido": "강원특별자치도",
    "sigungu": "강릉시",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "보건기관, 약국, 주민센터 및 면사무소",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "2013년 기사에서 수거장소 언급"
  },
  {
    "id": "125",
    "sido": "강원특별자치도",
    "sigungu": "고성군",
    "type": "없음",
    "ordinance": "-",
    "department": "보건소 보건행정과",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "보건소, 보건지소, 약국",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "2025년 기사에서 수거장소 언급"
  },
  {
    "id": "112",
    "sido": "강원특별자치도",
    "sigungu": "동해시",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "보건소, 주민센터, 지정 약국",
    "pharmacy": "-",
    "postbox": "O",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "폐의약품·불용의약품 검색 무결과"
  },
  {
    "id": "115",
    "sido": "강원특별자치도",
    "sigungu": "삼척시",
    "type": "없음",
    "ordinance": "-",
    "department": "보건소 예방의약담당",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "보건기관, 약국",
    "pharmacy": "-",
    "postbox": "O",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "2026년 시청 공지사항에서 언급"
  },
  {
    "id": "114",
    "sido": "강원특별자치도",
    "sigungu": "속초시",
    "type": "있음",
    "ordinance": "속초시 폐의약품 등 관리에 관한 조례",
    "department": "경제관광국 친환경과",
    "enacted": "2023-10-27",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "보건소, 시 소재 약국 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조",
    "checked": "2026-09-01",
    "note": "시장은 월 1회 이상 수거·운반·처리한다."
  },
  {
    "id": "123",
    "sido": "강원특별자치도",
    "sigungu": "양구군",
    "type": "있음",
    "ordinance": "양구군 폐의약품 처리에 관한 조례",
    "department": "행정복지국 환경과",
    "enacted": "2026-02-13",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "관내 약국, 보건소(보건지소 포함) 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": "군수는  분기 1회 이상 정기적으로 폐의약품을 수거한다"
  },
  {
    "id": "126",
    "sido": "강원특별자치도",
    "sigungu": "양양군",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "-",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "폐의약품·불용의약품 검색 무결과"
  },
  {
    "id": "118",
    "sido": "강원특별자치도",
    "sigungu": "영월군",
    "type": "있음(폐기물조례)",
    "ordinance": "영월군 폐기물관리에 관한 조례",
    "department": "환경위생과",
    "enacted": "2025-05-23",
    "revised": "2026-02-06",
    "disposal": "O",
    "collection": "약국, 보건기관, 읍·면사무소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제5조의2",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "110",
    "sido": "강원특별자치도",
    "sigungu": "원주시",
    "type": "있음",
    "ordinance": "원주시 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2020-12-31",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "약국, 보건소(지소·진료소 포함), 행정복지센터",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제6조",
    "checked": "2026-09-01",
    "note": "월 1회 이상 수거·운반·처리한다."
  },
  {
    "id": "124",
    "sido": "강원특별자치도",
    "sigungu": "인제군",
    "type": "있음",
    "ordinance": "인제군 불용의약품 관리에 관한 조례",
    "department": "도시건설국 환경보호과",
    "enacted": "2014-08-21",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "관내 약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제6조",
    "checked": "2026-09-01",
    "note": "월 1회 이상 운반하여야 한다."
  },
  {
    "id": "120",
    "sido": "강원특별자치도",
    "sigungu": "정선군",
    "type": "있음",
    "ordinance": "정선군 불용의약품 등의 관리에 관한 조례",
    "department": "보건소",
    "enacted": "2016-12-30",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "보건소, 군 소재 약국 등",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조, 제5조",
    "checked": "2026-09-01",
    "note": "월 한 차례 이상 거점 장소까지 운반"
  },
  {
    "id": "121",
    "sido": "강원특별자치도",
    "sigungu": "철원군",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "약국, 보건기관",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "2013년 기사에서 수거장소 언급"
  },
  {
    "id": "109",
    "sido": "강원특별자치도",
    "sigungu": "춘천시",
    "type": "있음",
    "ordinance": "춘천시 의약품 안전사용 조례",
    "department": "보건소 식품의약과",
    "enacted": "2021-05-20",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "보건소, 약국, 공동주택 및 행정복지센터",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항, 제6조",
    "checked": "2026-09-01",
    "note": "폐기물관리 조례에도 배출 규정 포함"
  },
  {
    "id": "113",
    "sido": "강원특별자치도",
    "sigungu": "태백시",
    "type": "없음",
    "ordinance": "-",
    "department": "",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "관내 약국 및 보건소, 보건지소",
    "pharmacy": "-",
    "postbox": "O",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "2023년 보건소 공지사항에서 수거장소 언급"
  },
  {
    "id": "119",
    "sido": "강원특별자치도",
    "sigungu": "평창군",
    "type": "없음",
    "ordinance": "-",
    "department": "환경위생과",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "관내 약국 및 읍.면사무소",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "2021년 기사에서 수거장소 언급"
  },
  {
    "id": "116",
    "sido": "강원특별자치도",
    "sigungu": "홍천군",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "행정복지센터, 보건소, 지정약국, 공동주택",
    "pharmacy": "-",
    "postbox": "O",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "2025년 군청 보도자료에서 언급"
  },
  {
    "id": "122",
    "sido": "강원특별자치도",
    "sigungu": "화천군",
    "type": "있음(폐기물조례)",
    "ordinance": "화천군 폐기물 관리 조례",
    "department": "환경과",
    "enacted": "조문 미상",
    "revised": "2025-02-07",
    "disposal": "O",
    "collection": "보건기관, 약국, 읍·면사무소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제8조 제2항 제1호",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "117",
    "sido": "강원특별자치도",
    "sigungu": "횡성군",
    "type": "있음",
    "ordinance": "횡성군 불용의약품 관리에 관한 조례",
    "department": "환경자원사업소",
    "enacted": "2017-04-20",
    "revised": "2022-12-16",
    "disposal": "O",
    "collection": "관내 약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": "거점 장소까지 월 1회 이상 운반하여야 한다"
  },
  {
    "id": "107",
    "sido": "경기도",
    "sigungu": "가평군",
    "type": "있음",
    "ordinance": "가평군 불용의약품 등 관리에 관한 조례",
    "department": "보건소 보건정책과",
    "enacted": "2012-05-30",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "군 소재 약국, 보건소",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제6조",
    "checked": "2026-09-01",
    "note": "경기 최초·전국에서도 매우 이른 제정(2012)"
  },
  {
    "id": "87",
    "sido": "경기도",
    "sigungu": "고양시",
    "type": "있음",
    "ordinance": "고양시 불용의약품 및 폐의약품 관리에 관한 조례",
    "department": "덕양구보건소 보건행정과",
    "enacted": "2023-11-17",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "시 소재 약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항~제3항, 제5조",
    "checked": "2026-09-01",
    "note": "제4조제3항에 액상제제 하수구 유입 방지 배출방법"
  },
  {
    "id": "88",
    "sido": "경기도",
    "sigungu": "과천시",
    "type": "있음",
    "ordinance": "과천시 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 질병관리과",
    "enacted": "2016-12-28",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "시 소재 약국, 시 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "83",
    "sido": "경기도",
    "sigungu": "광명시",
    "type": "있음(폐기물조례)",
    "ordinance": "광명시 폐기물 관리에 관한 조례",
    "department": "친환경사업본부 자원순환과",
    "enacted": "2021-07-01",
    "revised": "2024-07-04",
    "disposal": "O",
    "collection": "약국, 보건소",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제10조(생활계 유해폐기물 배출방법)",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "102",
    "sido": "경기도",
    "sigungu": "광주시",
    "type": "있음",
    "ordinance": "광주시 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건정책과",
    "enacted": "2021-04-07",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "시 소재 약국, 보건소(보건지소 포함), 읍·면·동 행정복지센터 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": "폐기물 관리 조례에도 규정 있음"
  },
  {
    "id": "89",
    "sido": "경기도",
    "sigungu": "구리시",
    "type": "있음(폐기물조례)",
    "ordinance": "구리시 폐기물관리에 관한 조례",
    "department": "환경관리사업소 자원순환과",
    "enacted": "조문 신설 2023-06-30",
    "revised": "2024-12-06",
    "disposal": "O",
    "collection": "약국, 보건소",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제7조제6항",
    "checked": "2026-09-01",
    "note": "포장지 제거 후 수거용기 배출"
  },
  {
    "id": "93",
    "sido": "경기도",
    "sigungu": "군포시",
    "type": "있음",
    "ordinance": "군포시 불용의약품 및 폐의약품 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2016-12-30",
    "revised": "2025-01-07",
    "disposal": "O",
    "collection": "시 소재 약국, 보건소, 동 행정복지센터, 공동주택 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제6조의2",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "100",
    "sido": "경기도",
    "sigungu": "김포시",
    "type": "있음",
    "ordinance": "김포시 불용의약품 등 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2016-10-31",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "시 소재 약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "90",
    "sido": "경기도",
    "sigungu": "남양주시",
    "type": "있음",
    "ordinance": "남양주시 불용의약품 등의 관리에 관한 조례",
    "department": "남양주보건소 보건정책과",
    "enacted": "2020-02-20",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "시 소재 약국, 보건소(보건지소 포함) 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "85",
    "sido": "경기도",
    "sigungu": "동두천시",
    "type": "있음",
    "ordinance": "동두천시 폐의약품 및 불용의약품 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2025-03-14",
    "revised": "2026-05-06",
    "disposal": "O",
    "collection": "약국, 보건소, 동 행정복지센터, 공동주택 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "82",
    "sido": "경기도",
    "sigungu": "부천시",
    "type": "있음(제한적)",
    "ordinance": "부천시 의약품 안전사용 조례",
    "department": "부천시보건소 건강정책과",
    "enacted": "2017-12-29",
    "revised": "(제정 후 개정 없음)",
    "disposal": "△",
    "collection": "약국, 보건소(거점)",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제5조제3호, 제7조",
    "checked": "2026-09-01",
    "note": "의약품안전사용 조례에 폐의약품 관리 근거·거점 규정만, 시민 배출방법·수거장소 상세 없음"
  },
  {
    "id": "79",
    "sido": "경기도",
    "sigungu": "성남시",
    "type": "있음",
    "ordinance": "성남시 불용의약품 등의 관리에 관한 조례",
    "department": "중원구보건소 보건행정과",
    "enacted": "2014-03-24",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "시 소재 약국, 보건소",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "78",
    "sido": "경기도",
    "sigungu": "수원시",
    "type": "없음",
    "ordinance": "-",
    "department": "보건소",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "-",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "O",
    "article": "-",
    "checked": "2026-09-01",
    "note": "2024년 수원시 보건소 게시글"
  },
  {
    "id": "92",
    "sido": "경기도",
    "sigungu": "시흥시",
    "type": "있음",
    "ordinance": "시흥시 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건정책과",
    "enacted": "2016-11-14",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "시 소재 약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "86",
    "sido": "경기도",
    "sigungu": "안산시",
    "type": "있음",
    "ordinance": "안산시 의약품 안전사용 조례",
    "department": "상록수보건소 보건정책과",
    "enacted": "2021-02-17",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "약국, 보건소, 보건지소, 동 행정복지센터",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제3조제2항",
    "checked": "2026-09-01",
    "note": "의약품안전사용 조례에 명확한 배출 규정 포함"
  },
  {
    "id": "99",
    "sido": "경기도",
    "sigungu": "안성시",
    "type": "있음",
    "ordinance": "안성시 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건위생과",
    "enacted": "2016-12-21",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "보건소, 시 소재 약국",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "81",
    "sido": "경기도",
    "sigungu": "안양시",
    "type": "있음",
    "ordinance": "안양시 불용의약품 등 관리에 관한 조례",
    "department": "동안구보건소 보건정책과",
    "enacted": "2014-10-21",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "시 소재 약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "103",
    "sido": "경기도",
    "sigungu": "양주시",
    "type": "있음",
    "ordinance": "양주시 불용의약품 및 폐의약품 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2026-03-03",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "시 소재 약국, 보건소(지소·진료소 포함), 읍·면·동 행정복지센터 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "108",
    "sido": "경기도",
    "sigungu": "양평군",
    "type": "있음(폐기물조례)",
    "ordinance": "양평군 폐기물관리 조례",
    "department": "환경교육국 청소과",
    "enacted": "조문 미상",
    "revised": "2024-07-10(전부개정)",
    "disposal": "O",
    "collection": "군 보건소·보건지소·보건진료소, 군 소재 약국, 읍·면사무소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제10조(폐의약품의 관리 등)",
    "checked": "2026-09-01",
    "note": "폐기물조례에 별도 조문"
  },
  {
    "id": "105",
    "sido": "경기도",
    "sigungu": "여주시",
    "type": "있음",
    "ordinance": "여주시 불용의약품 등 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2016-10-31",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "보건소·보건지소·보건진료소 등 (약국은 협력 노력)",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제5조",
    "checked": "2026-09-01",
    "note": "시민 배출조항은 약함, 약국은 직접 의무 아님"
  },
  {
    "id": "106",
    "sido": "경기도",
    "sigungu": "연천군",
    "type": "있음",
    "ordinance": "연천군 불용의약품 등의 관리 조례",
    "department": "보건의료원 보건사업과",
    "enacted": "2025-03-06",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "군 소재 약국, 보건의료원(지소·진료소 포함), 읍·면 행정복지센터 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "91",
    "sido": "경기도",
    "sigungu": "오산시",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "보건기관, 행정복지센터, 공공기관, 약국",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "2025년에 관련 조례가 폐지됨"
  },
  {
    "id": "96",
    "sido": "경기도",
    "sigungu": "용인시",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "행정복지센터., 구청 및 보건소",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "2024년 시청 시정소식에서 언급"
  },
  {
    "id": "94",
    "sido": "경기도",
    "sigungu": "의왕시",
    "type": "있음",
    "ordinance": "의왕시 불용의약품 등 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2016-11-14",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "시 소재 약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "80",
    "sido": "경기도",
    "sigungu": "의정부시",
    "type": "있음",
    "ordinance": "의정부시 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건정책과",
    "enacted": "2017-05-08",
    "revised": "2026-01-09",
    "disposal": "O",
    "collection": "약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "98",
    "sido": "경기도",
    "sigungu": "이천시",
    "type": "있음(폐기물조례)",
    "ordinance": "이천시 폐기물 관리에 관한 조례",
    "department": "환경수자원국 자원순환과",
    "enacted": "조문 미상",
    "revised": "2026-04-17",
    "disposal": "O",
    "collection": "약국, 보건소, 읍·면·동 행정복지센터",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제11조(폐의약품의 배출 및 처리 등)",
    "checked": "2026-09-01",
    "note": "폐기물조례에 별도 조문"
  },
  {
    "id": "97",
    "sido": "경기도",
    "sigungu": "파주시",
    "type": "있음",
    "ordinance": "파주시 불용의약품 등의 관리에 관한 조례",
    "department": "파주보건소 보건행정과",
    "enacted": "2016-12-23",
    "revised": "2017-09-22",
    "disposal": "O",
    "collection": "시 소재 약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "84",
    "sido": "경기도",
    "sigungu": "평택시",
    "type": "있음",
    "ordinance": "평택시 불용의약품 등 관리에 관한 조례",
    "department": "평택보건소 보건사업과",
    "enacted": "2016-06-03",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "시 소재 약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제6조",
    "checked": "2026-09-01",
    "note": "폐기물 관리 조례에도 규정 있음"
  },
  {
    "id": "104",
    "sido": "경기도",
    "sigungu": "포천시",
    "type": "있음",
    "ordinance": "포천시 불용의약품 등 관리에 관한 조례",
    "department": "경제환경국 기후환경과",
    "enacted": "2024-09-25",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "시 소재 약국, 보건소(지소·진료소 포함), 읍·면·동 행정복지센터 등",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "95",
    "sido": "경기도",
    "sigungu": "하남시",
    "type": "있음",
    "ordinance": "하남시 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건정책과",
    "enacted": "2020-11-30",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "시 소재 약국, 보건소(보건지소 포함) 등",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "101",
    "sido": "경기도",
    "sigungu": "화성시",
    "type": "있음",
    "ordinance": "화성시 불용의약품 및 폐의약품 관리에 관한 조례",
    "department": "기후에너지환경국 자원순환과",
    "enacted": "2022-04-28",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "시 소재 약국, 보건소, 행정복지센터 등",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "217",
    "sido": "경상남도",
    "sigungu": "거제시",
    "type": "있음",
    "ordinance": "거제시 불용의약품 등의 관리 조례",
    "department": "보건소 감염관리과",
    "enacted": "2019-04-11",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "227",
    "sido": "경상남도",
    "sigungu": "거창군",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "-",
    "pharmacy": "-",
    "postbox": "O",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "폐의약품·불용의약품 검색 무결과"
  },
  {
    "id": "222",
    "sido": "경상남도",
    "sigungu": "고성군",
    "type": "있음",
    "ordinance": "고성군 불용의약품 등의 관리에 관한 조례",
    "department": "보건소",
    "enacted": "2021-06-04",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "군 소재 약국 등 지정 수거함",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "215",
    "sido": "경상남도",
    "sigungu": "김해시",
    "type": "있음",
    "ordinance": "김해시 불용의약품 등의 관리에 관한 조례",
    "department": "김해시보건소 보건관리과",
    "enacted": "2017-03-24",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "관내 약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "223",
    "sido": "경상남도",
    "sigungu": "남해군",
    "type": "있음",
    "ordinance": "남해군 불용의약품 등의 관리에 관한 조례",
    "department": "해양환경국 환경과",
    "enacted": "2021-02-09",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "군 소재 약국, 군 보건소, 읍·면 행정복지센터",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "216",
    "sido": "경상남도",
    "sigungu": "밀양시",
    "type": "있음",
    "ordinance": "밀양시 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 감염병관리과",
    "enacted": "2019-05-09",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "읍·면·동 행정복지센터, 보건소, 약국 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "214",
    "sido": "경상남도",
    "sigungu": "사천시",
    "type": "있음",
    "ordinance": "사천시 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건위생과",
    "enacted": "2016-11-28",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "시 소재 약국, 시 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "225",
    "sido": "경상남도",
    "sigungu": "산청군",
    "type": "있음(폐기물조례)",
    "ordinance": "산청군 폐기물관리에 관한 조례",
    "department": "환경위생과 자원순환담당",
    "enacted": "조문 미상",
    "revised": "2022-12-01",
    "disposal": "O",
    "collection": "약국, 보건소(보건지소 등 포함)",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제6조제9항",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "218",
    "sido": "경상남도",
    "sigungu": "양산시",
    "type": "있음",
    "ordinance": "양산시 불용의약품 등의 관리에 대한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2016-12-30",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "시 소재 약국, 보건소",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "219",
    "sido": "경상남도",
    "sigungu": "의령군",
    "type": "있음",
    "ordinance": "의령군 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2016-11-09",
    "revised": "2017-10-10",
    "disposal": "O",
    "collection": "군 소재 약국, 보건소",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "212",
    "sido": "경상남도",
    "sigungu": "진주시",
    "type": "없음",
    "ordinance": "-",
    "department": "보건소 의약팀",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "약국, 보건소",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "2025년 보건소 Q&A에서 언급"
  },
  {
    "id": "221",
    "sido": "경상남도",
    "sigungu": "창녕군",
    "type": "있음",
    "ordinance": "창녕군 불용의약품 등의 관리에 관한 조례",
    "department": "관광환경국 환경위생과",
    "enacted": "2020-11-04",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "군 소재 약국(동의 시), 보건소(지소·진료소 포함), 읍·면사무소, 행정복지센터 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "211",
    "sido": "경상남도",
    "sigungu": "창원시",
    "type": "있음",
    "ordinance": "창원시 의약품 안전사용 및 불용의약품 등의 관리에 관한 조례",
    "department": "창원보건소 보건정책과",
    "enacted": "2021-07-15",
    "revised": "2024-02-08(명칭변경·통합)",
    "disposal": "O",
    "collection": "약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "213",
    "sido": "경상남도",
    "sigungu": "통영시",
    "type": "있음(폐기물조례)",
    "ordinance": "통영시 생활폐기물 관리에 관한 조례",
    "department": "수산환경국 자원순환과",
    "enacted": "조문 미상",
    "revised": "2024-09-30",
    "disposal": "O",
    "collection": "약국, 보건소(지소·진료소 포함), 읍·면사무소, 동주민센터, 행정복지센터",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "폐기물 배출방법 조항",
    "checked": "2026-09-01",
    "note": "무상 배출"
  },
  {
    "id": "224",
    "sido": "경상남도",
    "sigungu": "하동군",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "-",
    "pharmacy": "-",
    "postbox": "O",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "폐의약품·불용의약품 검색 무결과"
  },
  {
    "id": "220",
    "sido": "경상남도",
    "sigungu": "함안군",
    "type": "있음",
    "ordinance": "함안군 불용의약품 등의 관리 조례",
    "department": "보건소",
    "enacted": "2021-02-25",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "군 소재 약국, 보건소(지소·진료소 포함) 등",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "226",
    "sido": "경상남도",
    "sigungu": "함양군",
    "type": "있음",
    "ordinance": "함양군 불용의약품 등 관리 조례",
    "department": "보건소 보건행정과",
    "enacted": "2016-12-27",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "관내 약국, 보건소",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "228",
    "sido": "경상남도",
    "sigungu": "합천군",
    "type": "있음",
    "ordinance": "합천군 불용의약품 등의 관리 조례",
    "department": "보건소 보건정책과",
    "enacted": "2016-12-01",
    "revised": "2023-12-21",
    "disposal": "O",
    "collection": "약국, 보건소(지소·진료소 포함), 읍·면사무소 등",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "198",
    "sido": "경상북도",
    "sigungu": "경산시",
    "type": "있음(폐기물조례)",
    "ordinance": "경산시 폐기물관리 조례",
    "department": "경제환경국 자원순환과",
    "enacted": "조문 미상",
    "revised": "2026-01-01(전부개정)",
    "disposal": "O",
    "collection": "약국, 보건소, 읍·면·동 행정복지센터",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제5조(폐기물 배출방법)",
    "checked": "2026-09-01",
    "note": "무상 배출"
  },
  {
    "id": "190",
    "sido": "경상북도",
    "sigungu": "경주시",
    "type": "있음",
    "ordinance": "경주시 불용의약품 등 관리에 관한 조례",
    "department": "환경녹지국 자원순환과",
    "enacted": "2020-11-18",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "시 소재 약국, 시 보건소, 행정복지센터",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "204",
    "sido": "경상북도",
    "sigungu": "고령군",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "-",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "폐의약품·불용의약품 검색 무결과"
  },
  {
    "id": "193",
    "sido": "경상북도",
    "sigungu": "구미시",
    "type": "있음",
    "ordinance": "구미시 불용의약품 등 관리에 관한 조례",
    "department": "구미보건소 보건의료정책과",
    "enacted": "2025-02-05",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "시 소재 약국, 보건소, 행정복지센터",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "191",
    "sido": "경상북도",
    "sigungu": "김천시",
    "type": "없음",
    "ordinance": "-",
    "department": "보건소",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "보건기관, 행정복지센터, 약국",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "2021년 기사에서 수거장소 언급"
  },
  {
    "id": "197",
    "sido": "경상북도",
    "sigungu": "문경시",
    "type": "없음",
    "ordinance": "",
    "department": "보건소",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "약국, 보건기관",
    "pharmacy": "-",
    "postbox": "X",
    "trashbag": "X",
    "article": "-",
    "checked": "2026-09-01",
    "note": "폐기물 관리 조례에 '폐의약품'이 수수료 관련 언급만 있음"
  },
  {
    "id": "208",
    "sido": "경상북도",
    "sigungu": "봉화군",
    "type": "있음",
    "ordinance": "봉화군 불용의약품 및 폐의약품 관리에 관한 조례",
    "department": "보건소 보건정책과",
    "enacted": "2024-09-23",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "군 소재 약국, 보건소, 읍·면 행정복지센터, 공동주택, 경로당 등",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항~제3항, 제7조",
    "checked": "2026-09-01",
    "note": "제4조제3항에 액상제제 하수구 유입 방지 배출방법"
  },
  {
    "id": "196",
    "sido": "경상북도",
    "sigungu": "상주시",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "경로당 등",
    "pharmacy": "-",
    "postbox": "O",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "폐의약품·불용의약품 검색 무결과"
  },
  {
    "id": "205",
    "sido": "경상북도",
    "sigungu": "성주군",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "보건기관, 약국, 행정복지센터",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "성주군 공공데이터에 보관장소 파일 확인"
  },
  {
    "id": "192",
    "sido": "경상북도",
    "sigungu": "안동시",
    "type": "있음",
    "ordinance": "안동시 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건위생과",
    "enacted": "2018-03-02",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "202",
    "sido": "경상북도",
    "sigungu": "영덕군",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "약국, 보건기관, 공동주택",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "영덕군 공공데이터 및 2025년 기사 확인"
  },
  {
    "id": "201",
    "sido": "경상북도",
    "sigungu": "영양군",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "경로당, 행정복지센터, 보건기관, 약국",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "영양군 공공데이터 및 2025년 기사 확인"
  },
  {
    "id": "194",
    "sido": "경상북도",
    "sigungu": "영주시",
    "type": "있음",
    "ordinance": "영주시 불용의약품 등 관리에 관한 조례",
    "department": "보건소 감염병관리과",
    "enacted": "2025-12-29",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "시 소재 약국, 보건소, 행정복지센터, 경로당 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "195",
    "sido": "경상북도",
    "sigungu": "영천시",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "보건기관, 약국, 행정복지센터, 경로당 등",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "2023, 2025년 기사에서 언급"
  },
  {
    "id": "207",
    "sido": "경상북도",
    "sigungu": "예천군",
    "type": "있음",
    "ordinance": "예천군 불용의약품 및 폐의약품 관리에 관한 조례",
    "department": "보건소",
    "enacted": "2025-11-17",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "관내 약국, 보건소, 읍·면행정복지센터, 공동주택, 경로당 등",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": "별도로 예천군 폐기물 관리 조례도 존재"
  },
  {
    "id": "210",
    "sido": "경상북도",
    "sigungu": "울릉군",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "보건기관, 약국, 경로당",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "보건의료원 홈페이지에 안내"
  },
  {
    "id": "209",
    "sido": "경상북도",
    "sigungu": "울진군",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "보건기관, 행정복지센터, 약국, 경로당",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "2025년 기사에서 수거장소 언급"
  },
  {
    "id": "199",
    "sido": "경상북도",
    "sigungu": "의성군",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "보건기관, 행정복지센터, 노인복지관, 약국, 경로당, 재가노인복지센터",
    "pharmacy": "-",
    "postbox": "O",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "2024년 기사에서 수거장소 언급"
  },
  {
    "id": "203",
    "sido": "경상북도",
    "sigungu": "청도군",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "보건기관, 경로당",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "폐의약품 수거량에 따라 종량제 봉투 교환"
  },
  {
    "id": "200",
    "sido": "경상북도",
    "sigungu": "청송군",
    "type": "있음",
    "ordinance": "청송군 불용의약품 및 폐의약품 관리에 관한 조례",
    "department": "보건의료원",
    "enacted": "2025-07-01",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "관내 약국, 보건의료원(지소·진료소 포함), 읍·면사무소 등",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "206",
    "sido": "경상북도",
    "sigungu": "칠곡군",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "보건소, 보건지소, 경로당, 약국",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "2025년 군청 SNS에서 수거장소 언급"
  },
  {
    "id": "189",
    "sido": "경상북도",
    "sigungu": "포항시",
    "type": "있음",
    "ordinance": "포항시 불용의약품 등의 관리 조례",
    "department": "환경국 자원순환과",
    "enacted": "2013-10-15",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "약국, 보건소(남·북구) 등",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": "전국에서 매우 이른 제정(2013)"
  },
  {
    "id": "66",
    "sido": "광주광역시",
    "sigungu": "광산구",
    "type": "있음",
    "ordinance": "(전남광주통합특별시 광산구) 불용의약품 및 폐의약품 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2021-10-01",
    "revised": "2025-03-12 (2026-06-30 명칭변경)",
    "disposal": "O",
    "collection": "약국, 보건소, 행정복지센터, 공동주택 등",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": "별도로 광산구 폐기물관리 조례도 존재"
  },
  {
    "id": "64",
    "sido": "광주광역시",
    "sigungu": "남구",
    "type": "있음",
    "ordinance": "(전남광주통합특별시 남구) 불용의약품 등 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2023-06-30",
    "revised": "2026-06-30 (명칭변경)",
    "disposal": "O",
    "collection": "약국, 보건소, 동 행정복지센터, 공동주택 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "62",
    "sido": "광주광역시",
    "sigungu": "동구",
    "type": "있음",
    "ordinance": "(전남광주통합특별시 동구) 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 건강도시과",
    "enacted": "2017-08-07",
    "revised": "2021-02-05 (2026-07-01 명칭변경)",
    "disposal": "O",
    "collection": "구 소재 약국, 보건소, 동 행정복지센터",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제3항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "65",
    "sido": "광주광역시",
    "sigungu": "북구",
    "type": "있음",
    "ordinance": "(전남광주통합특별시 북구) 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2017-03-10",
    "revised": "2022-12-27 (2026-06-30 명칭변경)",
    "disposal": "O",
    "collection": "약국, 보건소, 동 행정복지센터, 복지관, 공동주택 등",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항, 제5조, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "63",
    "sido": "광주광역시",
    "sigungu": "서구",
    "type": "있음",
    "ordinance": "(전남광주통합특별시 서구) 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2022-08-20",
    "revised": "2026-07-01 (명칭변경)",
    "disposal": "O",
    "collection": "약국, 보건소, 동 행정복지센터, 공동주택 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "50",
    "sido": "대구광역시",
    "sigungu": "군위군",
    "type": "있음",
    "ordinance": "대구광역시 군위군 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2016-12-23",
    "revised": "2023-06-30",
    "disposal": "O",
    "collection": "군 소재 약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제6조제2항, 제7조",
    "checked": "2026-09-01",
    "note": "2016년 경북 군위군 시절 제정, 2023-07 대구 편입"
  },
  {
    "id": "45",
    "sido": "대구광역시",
    "sigungu": "남구",
    "type": "있음",
    "ordinance": "대구광역시 남구 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2019-06-20",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "구 소재 약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제5조제2항, 제6조",
    "checked": "2026-09-01",
    "note": "별도로 남구 폐기물관리 조례(2024-05-20)에도 폐의약품 관련 언급 있음"
  },
  {
    "id": "48",
    "sido": "대구광역시",
    "sigungu": "달서구",
    "type": "있음",
    "ordinance": "대구광역시달서구 불용의약품 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2011-12-30",
    "revised": "2025-04-01",
    "disposal": "O",
    "collection": "구 소재 약국, 구 보건소, 동 행정복지센터, 복지관, 공동주택 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제5조제2항, 제6조",
    "checked": "2026-09-01",
    "note": "대구 최초 제정(2011)"
  },
  {
    "id": "49",
    "sido": "대구광역시",
    "sigungu": "달성군",
    "type": "있음",
    "ordinance": "대구광역시 달성군 불용의약품 등 관리에 관한 조례",
    "department": "보건소 보건과",
    "enacted": "2017-03-30",
    "revised": "2024-04-01",
    "disposal": "O",
    "collection": "군 소재 약국, 보건소(지소·진료소 포함), 읍·면 행정복지센터",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제5조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "43",
    "sido": "대구광역시",
    "sigungu": "동구",
    "type": "있음",
    "ordinance": "대구광역시 동구 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2017-03-30",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "구 소재 약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제5조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "46",
    "sido": "대구광역시",
    "sigungu": "북구",
    "type": "있음",
    "ordinance": "대구광역시 북구 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건과",
    "enacted": "2021-04-30",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "구 소재 약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "44",
    "sido": "대구광역시",
    "sigungu": "서구",
    "type": "있음",
    "ordinance": "대구광역시 서구 폐의약품 처리에 관한 조례",
    "department": "복지생활국 생활환경과",
    "enacted": "2024-12-30",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "관내 약국, 보건소, 동 행정복지센터",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "47",
    "sido": "대구광역시",
    "sigungu": "수성구",
    "type": "있음",
    "ordinance": "대구광역시 수성구 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2022-11-10",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "구 소재 약국, 보건소, 동 행정복지센터",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "42",
    "sido": "대구광역시",
    "sigungu": "중구",
    "type": "없음",
    "ordinance": "",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "X",
    "collection": "행정복지센터, 보건소, 약국, 공동주택, 초등학교",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "2025년 기사에서 수거장소 언급"
  },
  {
    "id": "71",
    "sido": "대전광역시",
    "sigungu": "대덕구",
    "type": "있음",
    "ordinance": "대전광역시 대덕구 불용의약품 등의 관리에 관한 조례",
    "department": "경제환경국 자원농생명과",
    "enacted": "2023-12-08",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "구 소재 약국, 보건소, 구청, 행정복지센터 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "67",
    "sido": "대전광역시",
    "sigungu": "동구",
    "type": "있음",
    "ordinance": "대전광역시 동구 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 질병관리과",
    "enacted": "2017-10-11",
    "revised": "2021-12-28",
    "disposal": "O",
    "collection": "구 소재 약국, 보건소, 동 행정복지센터 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "69",
    "sido": "대전광역시",
    "sigungu": "서구",
    "type": "있음",
    "ordinance": "대전광역시 서구 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 정신의약과",
    "enacted": "2017-02-27",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "구 소재 약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "70",
    "sido": "대전광역시",
    "sigungu": "유성구",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "X",
    "collection": "구청, 행정복지센터, 보건기관, 유성노인복지관, 유성실버복지센터, 도서관",
    "pharmacy": "X",
    "postbox": "X",
    "trashbag": "X",
    "article": "-",
    "checked": "2026-09-01",
    "note": "2025년 유성구 블로그에 수거장소 언급"
  },
  {
    "id": "68",
    "sido": "대전광역시",
    "sigungu": "중구",
    "type": "있음",
    "ordinance": "대전광역시 중구 불용의약품등의 관리에 관한 조례",
    "department": "보건소 건강증진과",
    "enacted": "2017-07-10",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "구 소재 약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "37",
    "sido": "부산광역시",
    "sigungu": "강서구",
    "type": "있음(제한적)",
    "ordinance": "부산광역시 강서구 폐기물 관리 및 수수료 등에 관한 조례",
    "department": "문화환경국 자원순환과",
    "enacted": "-",
    "revised": "2024-09-24",
    "disposal": "△(규칙 위임)",
    "collection": "구청, 행정복지센터, 보건기관, 약국",
    "pharmacy": "-",
    "postbox": "X",
    "trashbag": "-",
    "article": "제9조제1항제6호",
    "checked": "2026-09-01",
    "note": "가정 내 폐의약품'을 배출품목으로만 열거, 방법·장소는 규칙 위임"
  },
  {
    "id": "36",
    "sido": "부산광역시",
    "sigungu": "금정구",
    "type": "있음(폐기물조례)",
    "ordinance": "부산광역시 금정구 폐기물 관리 및 수수료 등에 관한 조례",
    "department": "문화환경국 자원순환과",
    "enacted": "2015-12-15(조문 신설)",
    "revised": "2026-02-10",
    "disposal": "O",
    "collection": "약국, 보건소",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제6조제1항제7호",
    "checked": "2026-09-01",
    "note": "가정 배출 폐의약품 무상 배출. 동주민센터 미포함"
  },
  {
    "id": "41",
    "sido": "부산광역시",
    "sigungu": "기장군",
    "type": "있음",
    "ordinance": "부산광역시 기장군 불용의약품 및 폐의약품 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2025-11-07",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "군 소재 약국, 보건소, 읍·면 행정복지센터 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "32",
    "sido": "부산광역시",
    "sigungu": "남구",
    "type": "있음(폐기물조례)",
    "ordinance": "부산광역시 남구 폐기물관리 및 수수료 등에 관한 조례",
    "department": "일자리환경국 자원순환과",
    "enacted": "2011-11-04(조문 신설)",
    "revised": "2026-08-12",
    "disposal": "O",
    "collection": "약국, 보건소, 동행정복지센터 등 구청장 지정 장소",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제6조제1항제8호",
    "checked": "2026-09-01",
    "note": "부산에서 폐의약품 조문 최초 도입(2011). 무상 배출"
  },
  {
    "id": "28",
    "sido": "부산광역시",
    "sigungu": "동구",
    "type": "있음(폐기물조례)",
    "ordinance": "부산광역시 동구 폐기물관리 및 수수료 등에 관한 조례",
    "department": "문화체육관광국 환경청소위생과",
    "enacted": "2021 이전(조문)",
    "revised": "2025-07-10",
    "disposal": "O",
    "collection": "보건소, 약국, 동행정복지센터, 폐기물처리 담당부서 수거함",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제9조의3",
    "checked": "2026-09-01",
    "note": "폐의약품 등 생활계 유해폐기물의 처리 조문"
  },
  {
    "id": "31",
    "sido": "부산광역시",
    "sigungu": "동래구",
    "type": "있음(폐기물조례)",
    "ordinance": "부산광역시동래구 폐기물 관리 및 수수료 등에 관한 조례",
    "department": "문화환경국 자원순환과",
    "enacted": "2015-12-31(조문 신설)",
    "revised": "2025-04-25",
    "disposal": "O",
    "collection": "약국, 보건소, 구청, 동 행정복지센터",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제6조의5",
    "checked": "2026-09-01",
    "note": "가정 내 발생하는 폐의약품의 처리 조문. 무상 배출"
  },
  {
    "id": "30",
    "sido": "부산광역시",
    "sigungu": "부산진구",
    "type": "있음(폐기물조례)",
    "ordinance": "부산광역시 부산진구 폐기물관리 및 수수료 등에 관한 조례",
    "department": "문화경제국 자원순환과",
    "enacted": "조문 신설 시점 미상",
    "revised": "2024-10-18 (차기 2026-08-11 공포)",
    "disposal": "O",
    "collection": "보건소, 약국, 주민센터, 폐기물처리 담당부서·보건소 수거함",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제6조의4",
    "checked": "2026-09-01",
    "note": "폐의약품 등 생활계 유해폐기물의 처리 조문"
  },
  {
    "id": "33",
    "sido": "부산광역시",
    "sigungu": "북구",
    "type": "있음(폐기물조례)",
    "ordinance": "부산광역시 북구 폐기물 관리 및 수수료 등에 관한 조례",
    "department": "경제환경국 자원순환과",
    "enacted": "2024-07-03(조문 신설)",
    "revised": "2026-02-04",
    "disposal": "O",
    "collection": "구청, 동 행정복지센터, 보건소, 약국",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제6조의4",
    "checked": "2026-09-01",
    "note": "가정 내 발생하는 폐의약품의 처리 조문. 무상 배출"
  },
  {
    "id": "40",
    "sido": "부산광역시",
    "sigungu": "사상구",
    "type": "있음(폐기물조례)",
    "ordinance": "부산광역시 사상구 폐기물관리 및 수수료 등에 관한 조례",
    "department": "경제환경국 청소행정과",
    "enacted": "2015-12-03(조문 추정)",
    "revised": "2025-12-01 (조문 개정 2024-12-31)",
    "disposal": "O",
    "collection": "약국, 보건소, 동 행정복지센터",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제6조제1항제6호",
    "checked": "2026-09-01",
    "note": "가정 배출 폐의약품 무상 배출"
  },
  {
    "id": "35",
    "sido": "부산광역시",
    "sigungu": "사하구",
    "type": "있음",
    "ordinance": "부산광역시 사하구 불용의약품 및 폐의약품 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2014-04-08",
    "revised": "2024-07-05(전부개정, 명칭변경)",
    "disposal": "O",
    "collection": "구 소재 약국, 보건소, 동 행정복지센터, 공동주택 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": "별지서식 '폐의약품 보관·처리 대장' 포함"
  },
  {
    "id": "27",
    "sido": "부산광역시",
    "sigungu": "서구",
    "type": "있음",
    "ordinance": "부산광역시 서구 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2016-11-07",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "구 소재 약국, 보건소, 동 주민센터 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "39",
    "sido": "부산광역시",
    "sigungu": "수영구",
    "type": "있음(폐기물조례)",
    "ordinance": "부산광역시 수영구 폐기물 관리 및 수수료 등에 관한 조례",
    "department": "복지환경국 자원순환과",
    "enacted": "2022-12-20(조문 신설)",
    "revised": "2026-05-20",
    "disposal": "O",
    "collection": "1.보건소 2.약국 3.동 행정복지센터 4.폐기물처리 담당부서 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제8조의3",
    "checked": "2026-09-01",
    "note": "폐의약품의 처리 조문. 수수료 부과 제외 명시"
  },
  {
    "id": "38",
    "sido": "부산광역시",
    "sigungu": "연제구",
    "type": "있음",
    "ordinance": "부산광역시 연제구 폐의약품 등 관리에 관한 조례",
    "department": "교통환경국 자원순환과",
    "enacted": "2022-12-23",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "1.보건소 2.약국 3.동 행정복지센터 4.폐기물처리 담당부서 등",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": "제정 시 폐기물관리조례 제7조의2 삭제(통합)"
  },
  {
    "id": "29",
    "sido": "부산광역시",
    "sigungu": "영도구",
    "type": "있음",
    "ordinance": "부산광역시 영도구 의약품 안전사용 및 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2025-05-07",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "보건소, 약국, 동 행정복지센터 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "26",
    "sido": "부산광역시",
    "sigungu": "중구",
    "type": "있음",
    "ordinance": "부산광역시 중구 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건과",
    "enacted": "2024-05-09",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "구 소재 약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제5조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "34",
    "sido": "부산광역시",
    "sigungu": "해운대구",
    "type": "있음",
    "ordinance": "부산광역시 해운대구 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건정책과",
    "enacted": "2016-11-01",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "구 소재 약국, 구 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "231",
    "sido": "서울특별시",
    "sigungu": "-",
    "type": "없음",
    "ordinance": "-",
    "department": "보건의료정책과",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "주민센터, 보건소, 복지관, 공동주택 (스마트 서울맵)",
    "pharmacy": "X",
    "postbox": "O",
    "trashbag": "X",
    "article": "-",
    "checked": "2026-09-01",
    "note": "폐의약품 전용조례 없음,"
  },
  {
    "id": "23",
    "sido": "서울특별시",
    "sigungu": "강남구",
    "type": "있음",
    "ordinance": "서울특별시 강남구 폐의약품 처리에 관한 조례",
    "department": "복지생활국 자원순환과",
    "enacted": "2024-01-05",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "관내 약국, 보건소(보건지소 포함), 동 주민센터",
    "pharmacy": "X",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "25",
    "sido": "서울특별시",
    "sigungu": "강동구",
    "type": "있음",
    "ordinance": "서울특별시 강동구 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건의료과",
    "enacted": "2016-12-28",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "관내 약국, 보건소 등",
    "pharmacy": "X",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "9",
    "sido": "서울특별시",
    "sigungu": "강북구",
    "type": "있음",
    "ordinance": "서울특별시 강북구 폐의약품 처리에 관한 조례",
    "department": "문화생활국 청소행정과",
    "enacted": "2025-03-21",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "관내 약국, 보건소, 동 주민센터",
    "pharmacy": "X",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항~제3항, 제5조",
    "checked": "2026-09-01",
    "note": "제4조제3항에 액상제제 하수구 유입 방지 등 배출방법 상세"
  },
  {
    "id": "16",
    "sido": "서울특별시",
    "sigungu": "강서구",
    "type": "있음",
    "ordinance": "서울특별시 강서구 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 의약과",
    "enacted": "2011-09-27",
    "revised": "2026-04-08",
    "disposal": "O",
    "collection": "1.구 소재 약국 2.구 보건소 3.동 주민센터",
    "pharmacy": "X",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항 각 호, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "21",
    "sido": "서울특별시",
    "sigungu": "관악구",
    "type": "있음(폐기물조례)",
    "ordinance": "서울특별시 관악구 폐기물 관리 조례",
    "department": "청년문화국 청소행정과",
    "enacted": "2023-11-06(조문 신설)",
    "revised": "2025-12-30 (해당 조문 개정 2025-11-13)",
    "disposal": "O",
    "collection": "동 주민센터 폐의약품 수거용기, 우체통",
    "pharmacy": "X",
    "postbox": "O",
    "trashbag": "X",
    "article": "제12조의2",
    "checked": "2026-09-01",
    "note": "서울 자치구 중 우체통 배출 명시 유일. 약국 미포함"
  },
  {
    "id": "5",
    "sido": "서울특별시",
    "sigungu": "광진구",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "X",
    "collection": "행정복지센터, 보건지소, 노인종합복지관, 체육센터, 문화원 등",
    "pharmacy": "X",
    "postbox": "O",
    "trashbag": "X",
    "article": "-",
    "checked": "2026-09-01",
    "note": "광진구 보건소 홈페이지에서 확인"
  },
  {
    "id": "17",
    "sido": "서울특별시",
    "sigungu": "구로구",
    "type": "있음",
    "ordinance": "서울특별시 구로구 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 의약과",
    "enacted": "2017-07-13",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "구 소재 약국, 구 보건소",
    "pharmacy": "X",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "18",
    "sido": "서울특별시",
    "sigungu": "금천구",
    "type": "있음",
    "ordinance": "서울특별시 금천구 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 의약과",
    "enacted": "2018-02-27",
    "revised": "2025-01-03",
    "disposal": "O",
    "collection": "관내 약국, 보건소(보건지소 포함), 동 주민센터",
    "pharmacy": "X",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "11",
    "sido": "서울특별시",
    "sigungu": "노원구",
    "type": "있음",
    "ordinance": "서울특별시 노원구 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 의약과",
    "enacted": "2017-09-28",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "구 소재 약국, 구 보건소",
    "pharmacy": "X",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "10",
    "sido": "서울특별시",
    "sigungu": "도봉구",
    "type": "있음(폐기물조례)",
    "ordinance": "서울특별시 도봉구 폐기물 관리 조례",
    "department": "미래환경국 자원순환과",
    "enacted": "2023-02-23(조문 신설)",
    "revised": "2025-05-15",
    "disposal": "O",
    "collection": "구 소재 약국, 보건소, 동주민센터, 복지시설 등 폐의약품 수거용기",
    "pharmacy": "X",
    "postbox": "O",
    "trashbag": "X",
    "article": "제13조의2",
    "checked": "2026-09-01",
    "note": "폐기물관리조례 내 조문"
  },
  {
    "id": "6",
    "sido": "서울특별시",
    "sigungu": "동대문구",
    "type": "있음",
    "ordinance": "서울특별시 동대문구 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 의약과",
    "enacted": "2016-11-03",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "구 소재 약국, 구 보건소",
    "pharmacy": "X",
    "postbox": "O",
    "trashbag": "X",
    "article": "제5조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "20",
    "sido": "서울특별시",
    "sigungu": "동작구",
    "type": "있음",
    "ordinance": "서울특별시 동작구 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건의약과",
    "enacted": "2017-11-09",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "구 소재 약국, 보건소 등",
    "pharmacy": "X",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "14",
    "sido": "서울특별시",
    "sigungu": "마포구",
    "type": "있음(폐기물조례)",
    "ordinance": "서울특별시 마포구 폐기물관리 조례",
    "department": "행정관리국 청소행정과",
    "enacted": "2025-05-08(조문 신설)",
    "revised": "2025-12-26",
    "disposal": "O",
    "collection": "보건소, 동 주민센터 등 폐의약품 수거 용기",
    "pharmacy": "X",
    "postbox": "O",
    "trashbag": "X",
    "article": "제12조의2",
    "checked": "2026-09-01",
    "note": "폐기물관리조례 내 조문"
  },
  {
    "id": "13",
    "sido": "서울특별시",
    "sigungu": "서대문구",
    "type": "있음",
    "ordinance": "서울특별시 서대문구 폐의약품 처리에 관한 조례",
    "department": "스마트환경생활국 청소행정과",
    "enacted": "2023-08-02",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "구 소재 약국, 구 보건소, 동 주민센터",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "22",
    "sido": "서울특별시",
    "sigungu": "서초구",
    "type": "있음",
    "ordinance": "서울특별시 서초구 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 의료지원과",
    "enacted": "2010-04-26",
    "revised": "2016-09-22",
    "disposal": "O",
    "collection": "구 소재 약국, 구 보건소 등",
    "pharmacy": "X",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "4",
    "sido": "서울특별시",
    "sigungu": "성동구",
    "type": "있음",
    "ordinance": "서울특별시 성동구 불용의약품 관리에 관한 조례",
    "department": "보건소 보건의료과",
    "enacted": "2009-11-19",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "구 소재 약국, 구 보건소",
    "pharmacy": "X",
    "postbox": "O",
    "trashbag": "X",
    "article": "제5조제2항, 제6조",
    "checked": "2026-09-01",
    "note": "서울 자치구 중 최초 제정(2009)"
  },
  {
    "id": "8",
    "sido": "서울특별시",
    "sigungu": "성북구",
    "type": "있음",
    "ordinance": "서울특별시 성북구 폐의약품 처리에 관한 조례",
    "department": "안전생활국 청소행정과",
    "enacted": "2024-10-04",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "관내 약국, 보건소(보건지소 포함), 동 주민센터",
    "pharmacy": "X",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "24",
    "sido": "서울특별시",
    "sigungu": "송파구",
    "type": "있음",
    "ordinance": "서울특별시 송파구 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 의약과",
    "enacted": "2013-12-19",
    "revised": "2025-07-10",
    "disposal": "O",
    "collection": "구 소재 약국, 구 보건소",
    "pharmacy": "X",
    "postbox": "O",
    "trashbag": "X",
    "article": "제5조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "15",
    "sido": "서울특별시",
    "sigungu": "양천구",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "동 주민센터, 공동주택",
    "pharmacy": "X",
    "postbox": "O",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "양천구청 홈페이지에서 수거장소 언급"
  },
  {
    "id": "19",
    "sido": "서울특별시",
    "sigungu": "영등포구",
    "type": "있음(폐기물조례)",
    "ordinance": "서울특별시 영등포구 폐기물관리 조례",
    "department": "생활환경국 청소과",
    "enacted": "2025-07-17(조문 신설)",
    "revised": "2025-07-17",
    "disposal": "O",
    "collection": "보건소, 동 주민센터 등 폐의약품 수거 용기",
    "pharmacy": "X",
    "postbox": "O",
    "trashbag": "X",
    "article": "제10조의2",
    "checked": "2026-09-01",
    "note": "폐기물관리조례 내 조문"
  },
  {
    "id": "3",
    "sido": "서울특별시",
    "sigungu": "용산구",
    "type": "있음(폐기물조례)",
    "ordinance": "서울특별시 용산구 폐기물 관리 조례",
    "department": "생활지원국 청소행정과",
    "enacted": "2025-12-26(조문 신설)",
    "revised": "2025-12-26",
    "disposal": "O",
    "collection": "보건소, 동 주민센터 등 폐의약품 수거함",
    "pharmacy": "X",
    "postbox": "O",
    "trashbag": "X",
    "article": "제11조의2",
    "checked": "2026-09-01",
    "note": "폐기물관리조례 내 생활계 유해폐기물 조문"
  },
  {
    "id": "12",
    "sido": "서울특별시",
    "sigungu": "은평구",
    "type": "있음",
    "ordinance": "서울특별시 은평구 불용의약품 등의 관리에 관한 조례",
    "department": "교통환경국 자원순환과",
    "enacted": "2017-08-10",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "관내 약국, 보건소 등",
    "pharmacy": "X",
    "postbox": "O",
    "trashbag": "X",
    "article": "제5조제2항, 제6조",
    "checked": "2026-09-01",
    "note": "보건소 아닌 자원순환과 소관"
  },
  {
    "id": "1",
    "sido": "서울특별시",
    "sigungu": "종로구",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "구청사, 동주민센터, 보건소, 공동주택단지, 종로노인종합복지관",
    "pharmacy": "X",
    "postbox": "O",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "2023년 기사에서 수거장소 언급"
  },
  {
    "id": "2",
    "sido": "서울특별시",
    "sigungu": "중구",
    "type": "있음",
    "ordinance": "서울특별시 중구 불용의약품 등의 관리에 관한 조례",
    "department": "청소행정과",
    "enacted": "2013-07-19",
    "revised": "2020-01-01",
    "disposal": "O",
    "collection": "구 소재 약국, 구 보건소, 동 주민센터",
    "pharmacy": "X",
    "postbox": "O",
    "trashbag": "X",
    "article": "제5조제2항",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "7",
    "sido": "서울특별시",
    "sigungu": "중랑구",
    "type": "있음",
    "ordinance": "서울특별시 중랑구 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 의약과",
    "enacted": "2013-05-23",
    "revised": "2023-10-05",
    "disposal": "O",
    "collection": "구 소재 약국, 구 보건소",
    "pharmacy": "X",
    "postbox": "O",
    "trashbag": "X",
    "article": "제5조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "77",
    "sido": "세종특별자치시",
    "sigungu": "세종특별자치시",
    "type": "있음",
    "ordinance": "세종특별자치시 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건의료과",
    "enacted": "2019-12-16",
    "revised": "2023-12-18",
    "disposal": "O",
    "collection": "약국, 보건소(지소·센터 포함), 읍·면·동 행정복지센터 등",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": "단층제(시군구 없음)"
  },
  {
    "id": "73",
    "sido": "울산광역시",
    "sigungu": "남구",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "관내 약국, 행정복지센터, 보건기관",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "2026년 구보건소 SNS에서 언급"
  },
  {
    "id": "74",
    "sido": "울산광역시",
    "sigungu": "동구",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "행정복지센터, 보건소, 지정약국, 노인복지관, 공동주택단지",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "2024년 기사에서 언급"
  },
  {
    "id": "75",
    "sido": "울산광역시",
    "sigungu": "북구",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "보건기관, 약국",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "2022년 보건소 알림사항에서 언급"
  },
  {
    "id": "76",
    "sido": "울산광역시",
    "sigungu": "울주군",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "행정복지센터, 약국",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "2022년 기사에서 언급"
  },
  {
    "id": "72",
    "sido": "울산광역시",
    "sigungu": "중구",
    "type": "있음",
    "ordinance": "울산광역시 중구 불용의약품 관리에 관한 조례",
    "department": "보건소 건강관리과",
    "enacted": "2013-08-06",
    "revised": "2014-12-29",
    "disposal": "O",
    "collection": "구 소재 약국, 구 보건소",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제6조, 제7조",
    "checked": "2026-09-01",
    "note": "전국적으로 이른 제정(2013)"
  },
  {
    "id": "60",
    "sido": "인천광역시",
    "sigungu": "강화군",
    "type": "있음",
    "ordinance": "강화군 불용의약품 등 관리에 관한 조례",
    "department": "보건소",
    "enacted": "2020-10-14",
    "revised": "2021-12-31",
    "disposal": "O",
    "collection": "군 소재 약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제5조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "59",
    "sido": "인천광역시",
    "sigungu": "검단구",
    "type": "있음",
    "ordinance": "인천광역시 검단구 불용의약품 등 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2026-07-01",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "구 소재 약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제5조제2항, 제6조",
    "checked": "2026-09-01",
    "note": "舊 서구 검단 지역. 신설"
  },
  {
    "id": "57",
    "sido": "인천광역시",
    "sigungu": "계양구",
    "type": "있음",
    "ordinance": "인천광역시 계양구 불용의약품 등 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2016-12-30",
    "revised": "2021-04-09",
    "disposal": "O",
    "collection": "구 소재 약국, 보건소, 동 행정복지센터 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제5조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "55",
    "sido": "인천광역시",
    "sigungu": "남동구",
    "type": "있음",
    "ordinance": "남동구 의약품 안전사용 환경조성 조례",
    "department": "보건소 보건행정과",
    "enacted": "2025-09-22",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "보건소, 약국, 동 행정복지센터 등 폐의약품 수거함",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제6조제2호",
    "checked": "2026-09-01",
    "note": "전용 '불용의약품' 조례 대신 '의약품 안전사용' 조례에 배출 규정. 별도 폐기물관리 조례도 존재"
  },
  {
    "id": "53",
    "sido": "인천광역시",
    "sigungu": "미추홀구",
    "type": "있음",
    "ordinance": "인천광역시 미추홀구 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2017-03-06",
    "revised": "2018-05-21(명칭변경, 舊 남구→미추홀구)",
    "disposal": "O",
    "collection": "구 소재 약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제5조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "56",
    "sido": "인천광역시",
    "sigungu": "부평구",
    "type": "있음",
    "ordinance": "인천광역시부평구 불용의약품 등 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2017-04-17",
    "revised": "2023-11-13",
    "disposal": "O",
    "collection": "구 소재 약국, 구청, 보건소, 보건지소, 동 행정복지센터",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제5조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "58",
    "sido": "인천광역시",
    "sigungu": "서해구",
    "type": "있음",
    "ordinance": "인천광역시 서해구 불용의약품 등 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2017-09-29",
    "revised": "2026-06-29(명칭변경, 舊 서구→서해구)",
    "disposal": "O",
    "collection": "구 소재 약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제5조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "54",
    "sido": "인천광역시",
    "sigungu": "연수구",
    "type": "있음",
    "ordinance": "인천광역시 연수구 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2017-07-07",
    "revised": "2018-12-24",
    "disposal": "O",
    "collection": "동 행정복지센터, 보건소, 약국",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제5조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "52",
    "sido": "인천광역시",
    "sigungu": "영종구",
    "type": "있음(폐기물조례)",
    "ordinance": "인천광역시 영종구 폐기물 관리에 관한 조례",
    "department": "주민생활국 자원순환과",
    "enacted": "2026-07-01(조문 포함 제정)",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "약국, 보건소(보건지소 포함), 동 행정복지센터 등 전용수거함",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제6조제5항(생활계 유해폐기물 배출방법)",
    "checked": "2026-09-01",
    "note": "舊 중구 영종도 지역. 포장재 제거·액상 처리 등 배출방법 상세"
  },
  {
    "id": "61",
    "sido": "인천광역시",
    "sigungu": "옹진군",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "약국, 보건기관",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "-",
    "checked": "2026-09-01",
    "note": "인천 데이터 포털에서 확인"
  },
  {
    "id": "51",
    "sido": "인천광역시",
    "sigungu": "제물포구",
    "type": "있음",
    "ordinance": "인천광역시 제물포구 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2026-07-01",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "구 소재 약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제5조제2항, 제6조",
    "checked": "2026-09-01",
    "note": "舊 중구+동구 통합. 신설"
  },
  {
    "id": "179",
    "sido": "전남광주통합특별시",
    "sigungu": "강진군",
    "type": "있음(폐기물조례)",
    "ordinance": "강진군 폐기물 관리에 관한 조례",
    "department": "복지환경국 환경과",
    "enacted": "조문 신설 2025-10-13",
    "revised": "2025-10-13",
    "disposal": "O",
    "collection": "약국, 보건소·보건지소·보건진료소, 읍·면사무소",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제14조의2",
    "checked": "2026-09-01",
    "note": "무상 배출"
  },
  {
    "id": "175",
    "sido": "전남광주통합특별시",
    "sigungu": "고흥군",
    "type": "있음",
    "ordinance": "고흥군 불용의약품 및 폐의약품 관리에 관한 조례",
    "department": "보건소",
    "enacted": "2023-08-04",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "군 소재 약국, 보건소, 보건지소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "173",
    "sido": "전남광주통합특별시",
    "sigungu": "곡성군",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "보건기관",
    "pharmacy": "-",
    "postbox": "O",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "데이터 포털 기준"
  },
  {
    "id": "171",
    "sido": "전남광주통합특별시",
    "sigungu": "광양시",
    "type": "있음",
    "ordinance": "광양시 불용의약품 및 폐의약품 관리에 관한 조례",
    "department": "관광문화환경국 자원순환과",
    "enacted": "2026-02-04",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "약국, 보건소, 읍·면·동사무소, 공동주택 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제3조, 제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "174",
    "sido": "전남광주통합특별시",
    "sigungu": "구례군",
    "type": "있음",
    "ordinance": "구례군 불용의약품 및 폐의약품 관리에 관한 조례",
    "department": "보건의료원",
    "enacted": "2024-12-31",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "군 소재 약국, 보건의료원, 보건지소, 보건진료소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "170",
    "sido": "전남광주통합특별시",
    "sigungu": "나주시",
    "type": "있음",
    "ordinance": "나주시 불용의약품 및 폐의약품 관리에 관한 조례",
    "department": "보건소 질병관리과",
    "enacted": "2023-04-10",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "시 소재 약국, 보건소, 행정복지센터, 공동주택 등",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "172",
    "sido": "전남광주통합특별시",
    "sigungu": "담양군",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "보건소, 약구, 병원 등",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "2025년 기사에서 수거장소 언급"
  },
  {
    "id": "167",
    "sido": "전남광주통합특별시",
    "sigungu": "목포시",
    "type": "있음",
    "ordinance": "목포시 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건위생과",
    "enacted": "2019-04-15",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "182",
    "sido": "전남광주통합특별시",
    "sigungu": "무안군",
    "type": "있음(폐기물조례)",
    "ordinance": "무안군 폐기물 관리에 관한 조례",
    "department": "환경과 청소행정팀",
    "enacted": "조문 신설 2020-07-20",
    "revised": "2024-04-01",
    "disposal": "O",
    "collection": "약국, 보건소(보건지소 등 포함)",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "폐기물 배출방법 조항",
    "checked": "2026-09-01",
    "note": "무상 배출"
  },
  {
    "id": "176",
    "sido": "전남광주통합특별시",
    "sigungu": "보성군",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "약국, 보건기관",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "2010년 군청 공지사항에서 언급"
  },
  {
    "id": "169",
    "sido": "전남광주통합특별시",
    "sigungu": "순천시",
    "type": "있음",
    "ordinance": "순천시 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건의료과",
    "enacted": "2023-05-31",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "시 소재 약국, 보건소(지소·진료소 포함), 읍·면·동 행정복지센터 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "188",
    "sido": "전남광주통합특별시",
    "sigungu": "신안군",
    "type": "있음(폐기물조례)",
    "ordinance": "신안군 폐기물관리 조례",
    "department": "문화예술관광국 세계유산과",
    "enacted": "조문 신설 2018-02-07",
    "revised": "2025-07-07",
    "disposal": "O",
    "collection": "약국, 보건소·보건지소·보건진료소",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "폐기물 배출방법 조항",
    "checked": "2026-09-01",
    "note": "무상 배출"
  },
  {
    "id": "168",
    "sido": "전남광주통합특별시",
    "sigungu": "여수시",
    "type": "있음",
    "ordinance": "여수시 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2020-05-27",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "184",
    "sido": "전남광주통합특별시",
    "sigungu": "영광군",
    "type": "있음",
    "ordinance": "영광군 불용의약품 및 폐의약품 관리에 관한 조례",
    "department": "환경과",
    "enacted": "2025-07-08",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "군 소재 약국, 보건소, 공동주택 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "181",
    "sido": "전남광주통합특별시",
    "sigungu": "영암군",
    "type": "있음(제한적/구식)",
    "ordinance": "영암군 폐기물 관리에 관한 조례",
    "department": "안전건설환경국 환경기후과",
    "enacted": "조문 신설 2021-09-16",
    "revised": "2025-10-30",
    "disposal": "O(종량제봉투 방식)",
    "collection": "없음(종량제봉투로 배출)",
    "pharmacy": "X",
    "postbox": "X",
    "trashbag": "O",
    "article": "제6조제3항",
    "checked": "2026-09-01",
    "note": "불용의약품을 종량제봉투에 담아 배출하도록 규정(수거함 방식 아님). 전국에서 드문 사례"
  },
  {
    "id": "186",
    "sido": "전남광주통합특별시",
    "sigungu": "완도군",
    "type": "있음",
    "ordinance": "완도군 불용의약품 및 폐의약품 관리에 관한 조례",
    "department": "환경수질과",
    "enacted": "2024-02-08",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "군 소재 약국, 보건의료원, 보건지소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": "별도로 완도군 폐기물관리 등에 관한 조례도 존재"
  },
  {
    "id": "185",
    "sido": "전남광주통합특별시",
    "sigungu": "장성군",
    "type": "있음(폐기물조례)",
    "ordinance": "장성군 폐기물 관리에 관한 조례",
    "department": "관광복지국 환경과",
    "enacted": "조문 미상",
    "revised": "2023-05-31",
    "disposal": "O",
    "collection": "약국, 보건소·보건지소·보건진료소",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제14조(폐의약품의 처리 등)",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "178",
    "sido": "전남광주통합특별시",
    "sigungu": "장흥군",
    "type": "있음",
    "ordinance": "장흥군 불용의약품 및 폐의약품 관리에 관한 조례",
    "department": "보건소 질병관리과",
    "enacted": "2023-03-08",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "군 소재 약국, 보건소, 보건지소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "187",
    "sido": "전남광주통합특별시",
    "sigungu": "진도군",
    "type": "있음",
    "ordinance": "진도군 불용의약품 및 폐의약품 관리에 관한 조례",
    "department": "환경수질과",
    "enacted": "2024-05-16",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "군 소재 약국, 보건소, 보건지소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "183",
    "sido": "전남광주통합특별시",
    "sigungu": "함평군",
    "type": "있음",
    "ordinance": "함평군 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2023-09-27",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "군 소재 약국, 보건소(지소·진료소 포함), 읍·면사무소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": "별도로 함평군 생활폐기물 등의 관리에 관한 조례도 존재"
  },
  {
    "id": "180",
    "sido": "전남광주통합특별시",
    "sigungu": "해남군",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "-",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "폐의약품·불용의약품 검색 무결과"
  },
  {
    "id": "177",
    "sido": "전남광주통합특별시",
    "sigungu": "화순군",
    "type": "있음(폐기물조례)",
    "ordinance": "화순군 폐기물 관리 조례",
    "department": "환경과",
    "enacted": "조문 신설 2020-06-30",
    "revised": "2025-07-04",
    "disposal": "O",
    "collection": "약국, 보건소, 보건지소",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제6조의4",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "165",
    "sido": "전북특별자치도",
    "sigungu": "고창군",
    "type": "있음(폐기물조례)",
    "ordinance": "고창군 생활폐기물 등 처리 및 수수료 등의 부과·징수에 관한 조례",
    "department": "안전건설국 환경에너지과",
    "enacted": "조문 신설 2020-12-30",
    "revised": "2025-10-15",
    "disposal": "O",
    "collection": "읍·면사무소, 약국, 보건소(지소·진료소 포함)",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "생활계 유해폐기물 배출방법",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "154",
    "sido": "전북특별자치도",
    "sigungu": "군산시",
    "type": "있음",
    "ordinance": "군산시 불용의약품 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2017-04-25",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "시 소재 약국, 시 보건소",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "158",
    "sido": "전북특별자치도",
    "sigungu": "김제시",
    "type": "있음(폐기물조례)",
    "ordinance": "김제시 폐기물 관리 조례",
    "department": "복지환경국 자원순환과",
    "enacted": "조문 신설 2020-09-24",
    "revised": "2024-11-05",
    "disposal": "O",
    "collection": "약국, 보건소",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "폐기물 배출방법 조항",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "157",
    "sido": "전북특별자치도",
    "sigungu": "남원시",
    "type": "있음",
    "ordinance": "남원시 불용의약품 등 관리에 관한 조례",
    "department": "안전건설국 환경과",
    "enacted": "2024-07-12",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "시 소재 약국, 보건소(지소·진료소 포함), 읍·면·동 행정복지센터 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "161",
    "sido": "전북특별자치도",
    "sigungu": "무주군",
    "type": "있음",
    "ordinance": "무주군 불용의약품 등의 관리에 관한 조례",
    "department": "보건의료원 보건행정과",
    "enacted": "2020-05-15",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "군 소재 약국, 보건의료원(진료소·지소 포함) 등",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "166",
    "sido": "전북특별자치도",
    "sigungu": "부안군",
    "type": "있음",
    "ordinance": "부안군 불용의약품 등의 관리에 관한 조례",
    "department": "산업건설국 환경과",
    "enacted": "2020-11-13",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "군 소재 약국, 군 보건소(지소·진료소 포함), 부안읍 행정복지센터, 면사무소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "164",
    "sido": "전북특별자치도",
    "sigungu": "순창군",
    "type": "있음(폐기물조례)",
    "ordinance": "순창군 폐기물 관리에 관한 조례",
    "department": "경제산업국 환경위생과",
    "enacted": "조문 미상",
    "revised": "2026-08-18",
    "disposal": "O",
    "collection": "약국, 보건의료원(지소·진료소 포함) 지정수거함",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "폐기물 배출방법 조항",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "159",
    "sido": "전북특별자치도",
    "sigungu": "완주군",
    "type": "있음",
    "ordinance": "완주군 불용의약품 등 관리에 관한 조례",
    "department": "보건소 건강증진과",
    "enacted": "2020-12-31",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "관내 약국, 보건소(지소·진료소 포함), 행정복지센터",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "155",
    "sido": "전북특별자치도",
    "sigungu": "익산시",
    "type": "있음(폐기물조례)",
    "ordinance": "익산시 폐기물 관리 조례",
    "department": "녹색도시환경국 청소자원과",
    "enacted": "조문 신설 2016-02-15",
    "revised": "2024-12-26",
    "disposal": "O",
    "collection": "약국, 보건소(지소·진료소 포함), 행정복지센터",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "폐기물 배출방법 조항",
    "checked": "2026-09-01",
    "note": "무상 배출"
  },
  {
    "id": "163",
    "sido": "전북특별자치도",
    "sigungu": "임실군",
    "type": "있음(폐기물조례)",
    "ordinance": "임실군 폐기물 관리 조례",
    "department": "청소위생과",
    "enacted": "조문 미상",
    "revised": "2021-07-05",
    "disposal": "O",
    "collection": "약국, 보건소(보건의료원 포함)·보건지소·보건진료소, 읍·면사무소",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "폐기물 배출방법 조항",
    "checked": "2026-09-01",
    "note": "무상 배출"
  },
  {
    "id": "162",
    "sido": "전북특별자치도",
    "sigungu": "장수군",
    "type": "있음",
    "ordinance": "장수군 불용의약품 등 관리에 관한 조례",
    "department": "농산업건설국 환경과",
    "enacted": "2025-11-20",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "관내 약국, 보건의료원(지소·진료소 포함), 재활용도움센터 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "153",
    "sido": "전북특별자치도",
    "sigungu": "전주시",
    "type": "있음(폐기물조례)",
    "ordinance": "전주시 폐기물 관리 조례",
    "department": "자원순환녹지국 청소지원과",
    "enacted": "조문 신설 2020-07-10",
    "revised": "2025-09-30",
    "disposal": "O",
    "collection": "약국, 보건소",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "폐기물 배출방법 조항",
    "checked": "2026-09-01",
    "note": "별도 '전주시 의약품 안전사용 환경조성 조례'(2020-03-13)에 폐의약품 수거 안내사업 근거 있음"
  },
  {
    "id": "156",
    "sido": "전북특별자치도",
    "sigungu": "정읍시",
    "type": "있음",
    "ordinance": "정읍시 폐의약품 등 관리에 관한 조례",
    "department": "복지환경국 자원순환과",
    "enacted": "2022-12-15",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "약국, 보건소(지소·진료소), 행정복지센터, 공동주택 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "160",
    "sido": "전북특별자치도",
    "sigungu": "진안군",
    "type": "있음(폐기물조례)",
    "ordinance": "진안군 폐기물 관리에 관한 조례",
    "department": "안전환경국 환경과",
    "enacted": "조문 신설 2023-12-12",
    "revised": "2023-12-12",
    "disposal": "O",
    "collection": "약국, 보건소(지소·진료소 포함), 읍·면 행정복지센터",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "폐기물 배출방법 조항",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "230",
    "sido": "제주특별자치도",
    "sigungu": "서귀포시",
    "type": "있음(제한적/도조례)",
    "ordinance": "제주특별자치도 의약품 안전사용 환경조성에 관한 조례",
    "department": "안전건강실 보건정책과",
    "enacted": "2024-03-18",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "보건소, 약국, 재활용도움센터",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항제4호(시행계획 항목), 제6조",
    "checked": "2026-09-01",
    "note": "행정시(자치법규 제정권 없음). 도 조례에 폐의약품 처리"
  },
  {
    "id": "229",
    "sido": "제주특별자치도",
    "sigungu": "제주시",
    "type": "있음(제한적/도조례)",
    "ordinance": "제주특별자치도 의약품 안전사용 환경조성에 관한 조례",
    "department": "안전건강실 보건정책과",
    "enacted": "2024-03-18",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "보건소, 약국",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항제4호(시행계획 항목), 제6조",
    "checked": "2026-09-01",
    "note": "행정시(자치법규 제정권 없음). 도 조례에 폐의약품 처리"
  },
  {
    "id": "144",
    "sido": "충청남도",
    "sigungu": "계룡시",
    "type": "있음",
    "ordinance": "계룡시 불용의약품 등의 관리에 관한 조례",
    "department": "보건소",
    "enacted": "2016-10-31",
    "revised": "2023-12-11",
    "disposal": "O",
    "collection": "시 소재 약국, 시 보건소, 보건지소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "139",
    "sido": "충청남도",
    "sigungu": "공주시",
    "type": "있음",
    "ordinance": "공주시 불용의약품 등 관리에 관한 조례",
    "department": "경제문화국 자원순환과",
    "enacted": "2023-06-23",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "시 소재 약국, 보건소(보건지소 포함), 읍·면·동 행정복지센터 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "146",
    "sido": "충청남도",
    "sigungu": "금산군",
    "type": "있음",
    "ordinance": "금산군 불용의약품 등 관리에 관한 조례",
    "department": "산업환경국 환경위생과",
    "enacted": "2021-05-31",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "군 소재 약국, 보건소, 읍·면사무소",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제3항",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "143",
    "sido": "충청남도",
    "sigungu": "논산시",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "약국, 보건소",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "2010년 기사에서 수거장소 언급"
  },
  {
    "id": "145",
    "sido": "충청남도",
    "sigungu": "당진시",
    "type": "있음",
    "ordinance": "당진시 불용의약품 등의 관리에 관한 조례",
    "department": "농업환경국 자원순환과",
    "enacted": "2022-04-15",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "약국, 보건소, 아파트 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제6조",
    "checked": "2026-09-01",
    "note": "별도로 당진시 폐기물 관리 조례에도 폐의약품 언급"
  },
  {
    "id": "140",
    "sido": "충청남도",
    "sigungu": "보령시",
    "type": "있음",
    "ordinance": "보령시 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 감염병관리과",
    "enacted": "2020-08-20",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "약국, 보건소, 아파트 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "147",
    "sido": "충청남도",
    "sigungu": "부여군",
    "type": "있음",
    "ordinance": "부여군 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건위생과",
    "enacted": "2017-06-12",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "군 소재 약국, 군 보건소, 보건지소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "142",
    "sido": "충청남도",
    "sigungu": "서산시",
    "type": "있음",
    "ordinance": "서산시 불용의약품 등의 관리 조례",
    "department": "보건소 보건행정과",
    "enacted": "2015-03-12",
    "revised": "2020-11-10",
    "disposal": "O",
    "collection": "관내 약국, 보건소, 보건지소, 보건진료소, 읍·면·동 행정복지센터, 아파트 관리사무소",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "148",
    "sido": "충청남도",
    "sigungu": "서천군",
    "type": "있음",
    "ordinance": "서천군 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2023-08-10",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "군 소재 약국, 보건소, 읍·면 행정복지센터, 복지관, 경로당, 공동주택 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "141",
    "sido": "충청남도",
    "sigungu": "아산시",
    "type": "있음",
    "ordinance": "아산시 불용의약품 등 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2016-12-15",
    "revised": "2020-09-15",
    "disposal": "O",
    "collection": "시 소재 약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항",
    "checked": "2026-09-01",
    "note": "별도로 아산시 폐기물 관리 조례에도 폐의약품 언급"
  },
  {
    "id": "151",
    "sido": "충청남도",
    "sigungu": "예산군",
    "type": "있음",
    "ordinance": "예산군 불용의약품 등의 관리 조례",
    "department": "산업건설국 환경과",
    "enacted": "2018-03-30",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "군 소재 약국, 군 보건소, 관내 행정복지센터",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "138",
    "sido": "충청남도",
    "sigungu": "천안시",
    "type": "있음",
    "ordinance": "천안시 폐의약품 등 관리에 관한 조례",
    "department": "농업환경국 청소행정과",
    "enacted": "2021-11-15",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "약국, 보건소(지소·진료소), 행정복지센터, 아파트 관리사무소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "149",
    "sido": "충청남도",
    "sigungu": "청양군",
    "type": "있음(폐기물조례)",
    "ordinance": "청양군 폐기물 관리 조례",
    "department": "환경정책과",
    "enacted": "조문 미상",
    "revised": "2025-01-24(전부개정)",
    "disposal": "O",
    "collection": "보건기관, 약국",
    "pharmacy": "△",
    "postbox": "X",
    "trashbag": "X",
    "article": "생활계 유해폐기물 조문",
    "checked": "2026-09-01",
    "note": "축산 농가에 폐의약품 수거 지원"
  },
  {
    "id": "152",
    "sido": "충청남도",
    "sigungu": "태안군",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "약국",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "폐의약품·불용의약품 검색 무결과"
  },
  {
    "id": "150",
    "sido": "충청남도",
    "sigungu": "홍성군",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "보건기관, 약국",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "2016년 기사에서 수거장소 언급"
  },
  {
    "id": "135",
    "sido": "충청북도",
    "sigungu": "괴산군",
    "type": "있음",
    "ordinance": "괴산군 불용의약품 등 관리에 관한 조례",
    "department": "행정복지국 환경과",
    "enacted": "2021-03-26",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "군 소재 약국, 보건소, 보건지소",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "137",
    "sido": "충청북도",
    "sigungu": "단양군",
    "type": "있음(폐기물조례)",
    "ordinance": "단양군 폐기물 관리 조례",
    "department": "자원순환팀",
    "enacted": "조문 신설 2019-12-31",
    "revised": "2023-12-29",
    "disposal": "O",
    "collection": "약국, 보건소, 보건지소, 보건진료소",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "폐기물 배출방법 조항",
    "checked": "2026-09-01",
    "note": "무상 배출"
  },
  {
    "id": "130",
    "sido": "충청북도",
    "sigungu": "보은군",
    "type": "있음",
    "ordinance": "보은군 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2018-12-14",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "군 소재 약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제6조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "132",
    "sido": "충청북도",
    "sigungu": "영동군",
    "type": "있음(폐기물조례)",
    "ordinance": "영동군 폐기물 관리 조례",
    "department": "환경과",
    "enacted": "조문 신설 2020-12-31",
    "revised": "2024-05-07",
    "disposal": "O",
    "collection": "군 소재 약국, 군 보건소, 군 보건지소",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "폐기물 배출방법 조항",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "131",
    "sido": "충청북도",
    "sigungu": "옥천군",
    "type": "있음",
    "ordinance": "옥천군 불용의약품 등의 관리에 관한 조례",
    "department": "보건소 보건행정과",
    "enacted": "2020-07-10",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "군 소재 약국, 보건소(지소·진료소 포함) 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "136",
    "sido": "충청북도",
    "sigungu": "음성군",
    "type": "있음(폐기물조례)",
    "ordinance": "음성군 폐기물 관리 조례",
    "department": "청소위생과",
    "enacted": "조문 미상",
    "revised": "2024-11-15",
    "disposal": "O",
    "collection": "약국, 보건소, 보건지소, 보건진료소, 읍·면 행정복지센터",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제5조제6항",
    "checked": "2026-09-01",
    "note": "무상 배출"
  },
  {
    "id": "129",
    "sido": "충청북도",
    "sigungu": "제천시",
    "type": "없음",
    "ordinance": "-",
    "department": "-",
    "enacted": "-",
    "revised": "-",
    "disposal": "-",
    "collection": "보건기관, 약국",
    "pharmacy": "-",
    "postbox": "-",
    "trashbag": "-",
    "article": "-",
    "checked": "2026-09-01",
    "note": "2023년 기사에서 수거장소 언급"
  },
  {
    "id": "133",
    "sido": "충청북도",
    "sigungu": "증평군",
    "type": "있음(폐기물조례)",
    "ordinance": "증평군 폐기물 관리에 관한 조례",
    "department": "환경위생과",
    "enacted": "조문 미상",
    "revised": "2025-05-09",
    "disposal": "O",
    "collection": "약국, 보건소",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "폐기물 배출방법 조항",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "134",
    "sido": "충청북도",
    "sigungu": "진천군",
    "type": "있음(폐기물조례)",
    "ordinance": "진천군 폐기물 관리에 관한 조례",
    "department": "경제환경국 식산업자원과",
    "enacted": "-",
    "revised": "2024-12-06",
    "disposal": "X",
    "collection": "약국, 보건소, 행정복지센터, 공동주택 등",
    "pharmacy": "-",
    "postbox": "X",
    "trashbag": "X",
    "article": "제2조제9호, 제6조제7항",
    "checked": "2026-09-01",
    "note": ""
  },
  {
    "id": "127",
    "sido": "충청북도",
    "sigungu": "청주시",
    "type": "있음",
    "ordinance": "청주시 불용의약품 등의 관리에 관한 조례",
    "department": "상당보건소 보건정책과",
    "enacted": "2017-04-07",
    "revised": "(제정 후 개정 없음)",
    "disposal": "O",
    "collection": "약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "X",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": "청원군(2014 폐지)은 청주시로 통합"
  },
  {
    "id": "128",
    "sido": "충청북도",
    "sigungu": "충주시",
    "type": "있음",
    "ordinance": "충주시 불용의약품 등 관리에 관한 조례",
    "department": "보건소 보건과",
    "enacted": "2023-08-11",
    "revised": "2025-05-16",
    "disposal": "O",
    "collection": "시 소재 병·의원, 약국, 보건소 등",
    "pharmacy": "O",
    "postbox": "O",
    "trashbag": "X",
    "article": "제4조제2항, 제5조",
    "checked": "2026-09-01",
    "note": ""
  }
];
